name: Comprimir_Descomprimir_Arquivos
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  archive: ^2.0.13
  path: ^1.6.4
#versões das dependcias adicionadas ao projeto
dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
